### ISSUE TITLE
Misses uses of deprecated images in blocks other than `machine:`?

### ISSUE THREAD

**Issue by OscarBocking** [CircleCI-Public/image-updater#11]
eg. our config that this script would not identify:
```
jobs:
  build_image:
      docker:
      - image: docker:19.03.13
      steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
```

Logs:
`No entry for "machine:" found`
