### ISSUE TITLE
Change to use compiled version to check

### ISSUE THREAD

**Issue by angeliski** [CircleCI-Public/image-updater#16]
Hey team! Nice tool

We are trying to use in our projects, but we got some issues when the executor is defined in an orb.

For example:
```yaml
  build:
    parameters:
      environment_env:
        type: steps
        default: []
    executor: gcp-gcr/default
    environment:
      GOOGLE_COMPUTE_ZONE: us-central1-a
      AWS_DEFAULT_REGION: us-east-1
      DOCKER_BUILDKIT: 1
```

You can't check, but when the compiled version is showed:
```yaml
  build:
    machine:
      image: ubuntu-2004:202201-02
    environment:
    - GOOGLE_COMPUTE_ZONE: us-central1-a
    - AWS_DEFAULT_REGION: us-east-1
    - DOCKER_BUILDKIT: 1
```

I understand it is very difficult to handle all orbs, but maybe we can put a path to open an issue in the repository?

I don't know if we have a simple way to get the compiled YAML too, but I can try to look to send a PR for that
